/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/logout": {
    /** End the session on this device */
    post: operations["logout"];
  };
  "/auth/me": {
    /** The session's own app_user */
    get: operations["me"];
  };
  "/weddings": {
    /** Create a wedding and the creator's membership in it */
    post: operations["create"];
  };
  "/weddings/{weddingId}": {
    /** The wedding, for a caller who is a member of it */
    get: operations["read"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    readonly CreateWeddingRequest: {
      /**
       * @description The bride's name
       * @example 이신부
       */
      readonly brideName: string;
      /**
       * @description The groom's name
       * @example 김신랑
       */
      readonly groomName: string;
      /**
       * Format: date
       * @description The wedding date
       * @example 2026-10-10
       */
      readonly weddingDate: string;
    };
    readonly MeResponse: {
      /** Format: int64 */
      readonly id: number;
      readonly name?: string | null;
    };
    readonly ProblemDetail: {
      readonly detail?: string | null;
      /** Format: uri */
      readonly instance?: string | null;
      readonly properties?: {
        [key: string]: unknown;
      } | null;
      /** Format: int32 */
      readonly status?: number;
      readonly title?: string | null;
      /** Format: uri */
      readonly type?: string;
    };
    readonly WeddingResponse: {
      readonly brideName: string;
      readonly groomName: string;
      /** Format: int64 */
      readonly id: number;
      /** Format: date */
      readonly weddingDate: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** End the session on this device */
  logout: {
    responses: {
      /** @description The session is over, whether or not there was one. */
      204: {
        content: never;
      };
    };
  };
  /** The session's own app_user */
  me: {
    responses: {
      /** @description The session resolved. */
      200: {
        content: {
          readonly "*/*": components["schemas"]["MeResponse"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** Create a wedding and the creator's membership in it */
  create: {
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateWeddingRequest"];
      };
    };
    responses: {
      /** @description The wedding and the caller's membership were created. */
      201: {
        content: {
          readonly "*/*": components["schemas"]["WeddingResponse"];
        };
      };
      /** @description A blank or over-long name, an unstorable date, or a body that could not be read. */
      400: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** The wedding, for a caller who is a member of it */
  read: {
    parameters: {
      path: {
        weddingId: number;
      };
    };
    responses: {
      /** @description The caller is a member of this wedding. */
      200: {
        content: {
          readonly "*/*": components["schemas"]["WeddingResponse"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No such wedding — which is also the answer when it exists and the caller is not a member of it, and when it has been deleted. */
      404: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
}
