/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/logout": {
    /** End the session on this device */
    post: operations["logout"];
  };
  "/auth/me": {
    /** The session's own app_user */
    get: operations["me"];
  };
  "/weddings": {
    /** The weddings the caller holds a seat in, newest first */
    get: operations["list"];
    /** Create a wedding, both of its seats and its free subscription term */
    post: operations["create"];
  };
  "/weddings/{weddingId}": {
    /** The wedding and its two seats, for a caller who holds one of them */
    get: operations["read"];
  };
  "/weddings/{weddingId}/guests": {
    /** The wedding's ledger, filtered by side and attendance */
    get: operations["listGuests"];
    /** Add a guest to the ledger */
    post: operations["createGuest"];
  };
  "/weddings/{weddingId}/headcount": {
    /** The wedding's 식대 인원, and its 보증인원 when one is set */
    get: operations["readHeadcount"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    readonly CreateGuestRequest: {
      /**
       * @description 배려사항 — belongs to the person and carries forward to seating
       * @example 휠체어 좌석
       */
      readonly accessibilityNote?: string | null;
      /**
       * @description As entered — normalising for matching is the matcher's job
       * @example 010-1234-5678
       */
      readonly contact?: string | null;
      /** @description 예상 참석 여부. Omitted, it is 참석 — the couple corrects what they hear */
      readonly expectedAttending?: boolean | null;
      /**
       * Format: int32
       * @description 참석 인원, this guest included — not a companion count. Omitted, it is 1
       * @example 2
       */
      readonly expectedPartySize?: number | null;
      /**
       * @description One of the seven aggregation groups. Omitted, the guest is OTHER (기타)
       * @enum {string|null}
       */
      readonly groupCategory?: "FAMILY" | "RELATIVE" | "COUSIN" | "PARENTS_GUEST" | "FRIEND" | "COWORKER" | "OTHER";
      /**
       * @description The couple's own label for the group. Never aggregated on
       * @example 대학교 동아리 친구들
       */
      readonly groupLabel?: string | null;
      /**
       * @description The guest's name — the one thing the couple must type
       * @example 김영수
       */
      readonly name: string;
      /**
       * @description 신랑측 or 신부측. Required: there is no value that means 'not stated'
       * @enum {string}
       */
      readonly side: "GROOM" | "BRIDE";
    };
    readonly CreateWeddingRequest: {
      /**
       * @description The caller's own name, as it should read on the ledger
       * @example 김신랑
       */
      readonly name: string;
      /**
       * @description Which seat the caller is taking — 신랑 or 신부. Never their partner's
       * @enum {string}
       */
      readonly side: "GROOM" | "BRIDE";
      /**
       * Format: date
       * @description The wedding date
       * @example 2026-10-10
       */
      readonly weddingDate: string;
    };
    readonly GuestMutationResponse: {
      readonly guest: components["schemas"]["GuestResponse"];
      readonly headcount: components["schemas"]["HeadcountResponse"];
    };
    readonly GuestResponse: {
      readonly accessibilityNote?: string | null;
      readonly contact?: string | null;
      readonly expectedAttending: boolean;
      /** Format: int32 */
      readonly expectedPartySize: number;
      /** @enum {string} */
      readonly groupCategory: "FAMILY" | "RELATIVE" | "COUSIN" | "PARENTS_GUEST" | "FRIEND" | "COWORKER" | "OTHER";
      readonly groupLabel?: string | null;
      /** Format: int64 */
      readonly id: number;
      readonly name: string;
      /** @enum {string} */
      readonly side: "GROOM" | "BRIDE";
    };
    readonly HeadcountResponse: {
      /** Format: int32 */
      readonly guaranteedHeadcount?: number | null;
      /** Format: int32 */
      readonly mealHeadcount: number;
    };
    readonly MeResponse: {
      /** Format: int64 */
      readonly id: number;
      readonly name?: string | null;
    };
    readonly ProblemDetail: {
      readonly detail?: string | null;
      /** Format: uri */
      readonly instance?: string | null;
      readonly properties?: {
        [key: string]: unknown;
      } | null;
      /** Format: int32 */
      readonly status?: number;
      readonly title?: string | null;
      /** Format: uri */
      readonly type?: string;
    };
    readonly WeddingResponse: {
      /** Format: int64 */
      readonly id: number;
      readonly seats: readonly components["schemas"]["WeddingSeatResponse"][];
      /** Format: date */
      readonly weddingDate: string;
    };
    readonly WeddingSeatResponse: {
      readonly name?: string | null;
      /** @enum {string} */
      readonly side: "GROOM" | "BRIDE";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** End the session on this device */
  logout: {
    responses: {
      /** @description The session is over, whether or not there was one. */
      204: {
        content: never;
      };
    };
  };
  /** The session's own app_user */
  me: {
    responses: {
      /** @description The session resolved. */
      200: {
        content: {
          readonly "*/*": components["schemas"]["MeResponse"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** The weddings the caller holds a seat in, newest first */
  list: {
    responses: {
      /** @description The caller's weddings — an empty array when they have none. */
      200: {
        content: {
          readonly "*/*": readonly components["schemas"]["WeddingResponse"][];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** Create a wedding, both of its seats and its free subscription term */
  create: {
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateWeddingRequest"];
      };
    };
    responses: {
      /** @description The wedding, the caller's seat, their partner's empty seat and a FREE term were created. */
      201: {
        content: {
          readonly "*/*": components["schemas"]["WeddingResponse"];
        };
      };
      /** @description A blank or over-long name, an unstorable date, or a body that could not be read. */
      400: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description The caller already belongs to a wedding; a person belongs to exactly one. */
      409: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** The wedding and its two seats, for a caller who holds one of them */
  read: {
    parameters: {
      path: {
        weddingId: number;
      };
    };
    responses: {
      /** @description The caller holds a seat in this wedding. */
      200: {
        content: {
          readonly "*/*": components["schemas"]["WeddingResponse"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No such wedding — which is also the answer when it exists and the caller holds no seat in it, and when it has been deleted. */
      404: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** The wedding's ledger, filtered by side and attendance */
  listGuests: {
    parameters: {
      query?: {
        /** @description 신랑측 or 신부측. Sent at most once; omitted or empty, both sides */
        side?: "GROOM" | "BRIDE";
        /** @description 참석 or 불참. Sent at most once; omitted or empty, both */
        attendance?: "ATTENDING" | "NOT_ATTENDING";
      };
      path: {
        weddingId: number;
      };
    };
    responses: {
      /** @description The whole ledger, oldest first — an empty array when the couple has entered nobody yet. */
      200: {
        content: {
          readonly "*/*": readonly components["schemas"]["GuestResponse"][];
        };
      };
      /** @description A `side` or `attendance` value outside its set. */
      400: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No such wedding — which is also the answer when it exists and the caller is not a member of it, and when it has been deleted. */
      404: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** Add a guest to the ledger */
  createGuest: {
    parameters: {
      path: {
        weddingId: number;
      };
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateGuestRequest"];
      };
    };
    responses: {
      /** @description The guest was added to this wedding's ledger. */
      201: {
        content: {
          readonly "*/*": components["schemas"]["GuestMutationResponse"];
        };
      };
      /** @description A blank or over-long name, a party size below 1, an over-long optional field, or a body that could not be read. */
      400: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No such wedding — which is also the answer when it exists and the caller is not a member of it, and when it has been deleted. */
      404: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
  /** The wedding's 식대 인원, and its 보증인원 when one is set */
  readHeadcount: {
    parameters: {
      path: {
        weddingId: number;
      };
    };
    responses: {
      /** @description The recomputed number. `mealHeadcount` is 0 for a ledger with nobody in it, and `guaranteedHeadcount` is absent until the couple has agreed one with their venue. */
      200: {
        content: {
          readonly "*/*": components["schemas"]["HeadcountResponse"];
        };
      };
      /** @description No session, or an expired or revoked one. */
      401: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description No such wedding — which is also the answer when it exists and the caller is not a member of it, and when it has been deleted. */
      404: {
        content: {
          readonly "*/*": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
}
