-- Donghaeng v1 baseline schema.
--
-- This file is BOTH a script and a typing manuscript. Flyway applies it in the
-- test suite and nowhere else; every real database gets it typed by hand
-- (notes/2026-08-09-decision-schema-ownership.md). There is no second copy.
--
-- APPLYING BY HAND: wrap the whole file in an explicit
--     BEGIN;  ... COMMIT;
-- Flyway supplies that transaction here, so it is deliberately not written
-- below — a BEGIN inside a Flyway migration ends Flyway's own transaction
-- early and de-couples the schema change from the history row. On Postgres,
-- DDL is transactional, so the hand-typed BEGIN/COMMIT fully recovers the
-- property that a half-applied change cannot survive.
--
-- Column sizes are load-bearing and are not checked by anything.
-- `ddl-auto: validate` compares JDBC type codes only — not length, precision,
-- scale or nullability — so a mistyped varchar(20) under a length = 255
-- mapping passes validation and then fails at INSERT on a long 하객 이름.
-- Read the sizes; nothing downstream will read them for you.
--
-- Two rules the shape of this file encodes:
--   * `side` is the only Postgres enum. Its value set is closed forever.
--     group_category, source, status and provider are varchar with
--     application-level validation, so adding a value is a deploy and not an
--     ALTER TYPE.
--   * Every wedding-scoped aggregate root carries wedding_id. Anything reached
--     only through its root does not — hence guest_change has it. The one
--     exception is guest_meal_count, which is NOT a root and carries the column
--     purely as an integrity device; read the block on that table before citing
--     it either way.
--
-- Defaults are deliberately absent. "Expected attendance defaults to 참석" is
-- application policy (notes/2026-08-06-design-ledger-and-import.md §4); a DB
-- default would be a second copy of the same rule in a place no test reads.
--
-- Tables NOT here, and why, in notes/ terms:
--   session, wedding invite, vendor template — their columns follow from
--   mechanisms that are not designed yet (#37, #9, #23). Adding them as
--   CREATE TABLE later is cheaper than ALTERing a guess.
--   RsvpResponse / ResponseMatch — dropped from v1 (2026-08-06).
--   SharedLink / GuestLink — deferred from v1 (2026-08-06).
--
-- One COLUMN not here, for the same kind of reason:
--   guest.lifecycle (PROVISIONAL / ACTIVE) — it has no trigger in v1, because
--   the only thing that mints a provisional guest is an unmatched RSVP-link
--   response and the links are deferred. Worse, 2026-08-03 §4 defines
--   PROVISIONAL as "expected slots empty by construction", and this file makes
--   expected_attending and expected_party_size NOT NULL — so the column would
--   have named a state the same file makes unrepresentable. It returns with the
--   links, as an ALTER, alongside whatever makes the expected slots optional.

-- Closed forever: a Korean wedding has a 신랑 side and a 신부 side.
create type wedding_side as enum ('GROOM', 'BRIDE');


-- ---------------------------------------------------------------------------
-- Identity. Outside every wedding — a person belongs to themselves, and may
-- belong to several weddings (the session never knows the wedding).
-- ---------------------------------------------------------------------------

create table app_user (
    id                bigint generated by default as identity primary key,
    -- Nullable on purpose: Kakao and Naver treat email as an optional consent
    -- scope, so it may never arrive. When it does it is the merge key for the
    -- same person arriving via a second provider
    -- (notes/2026-08-06-design-ledger-and-import.md §3).
    --
    -- NARROWED 2026-08-11: only an email the provider ASSERTS AS VERIFIED is
    -- written here. Kakao returns is_email_verified as a separate field and can
    -- hand back an unverified address; Naver's is user-editable. Merging on
    -- either is a full ledger takeover with no token and no expiry, so an
    -- unverified address is simply not stored and the account stands alone.
    -- There is no account-linking flow in v1 — a second provider carrying an
    -- unverified email just yields a second account, and multiple NULLs do not
    -- collide in the partial index below. That is a constraint on #37; the
    -- schema only has to permit it cleanly.
    email             varchar(255),
    -- WHICH provider asserted that verification: GOOGLE or KAKAO. NAVER IS NOT
    -- A LEGAL VALUE — see ck_app_user_email_verifier_known below.
    -- The audit trail for why we trusted this address as a merge key — without
    -- it, "we merged two accounts" has no record of whose word we took, and the
    -- narrowing above becomes unverifiable after the fact.
    email_verified_by varchar(20),
    name              varchar(100),
    created_at        timestamptz not null,
    -- The three columns above are mutable: an email can arrive on a later
    -- provider merge, and a display name changes at the provider. `wedding` and
    -- `guest` carry both stamps and this must not be the odd one out.
    updated_at        timestamptz not null,
    -- The pairing is total in both directions: a stored email always came from
    -- a provider that vouched for it, and a verifier without an address is
    -- nonsense. Unlike guest_change's channel-FK rule below, this one is a plain
    -- biconditional with no third case to get wrong later, so it is worth a
    -- constraint rather than a comment. Note its reach: it proves the verifier
    -- was RECORDED, not that the provider's flag was actually read — that part
    -- is #37's, and this makes forgetting it loud rather than silent.
    constraint ck_app_user_email_verified_by
        check ((email is null) = (email_verified_by is null)),
    -- WHICH verifiers exist, and this is the one place in the file where "adding
    -- a value should be a deploy, not an ALTER TYPE" cuts FOR a constraint
    -- rather than against one. Every other value set here — group_category,
    -- source, status, provider — is open because a new value is just a new word.
    -- A name in THIS list is a claim that a company checked mailbox control, so
    -- adding one must be deliberate and reviewed; the ALTER is the point.
    --
    -- NAVER is absent because it can never be true: Naver's profile API returns
    -- an email with no verification flag at all and the address is
    -- user-editable. Without this constraint the biconditional above makes
    -- writing it the path of LEAST resistance — a verifier is demanded whenever
    -- an email is present, so a #37 developer holding a Naver address chooses
    -- between dropping the address and naming NAVER. Naming it reopens the
    -- takeover in full: edit the Naver account's email to the victim's address,
    -- log in, get merged onto their app_user and every membership on it.
    --
    -- NULL passes this check (SQL unknown), which is right: an account with no
    -- email has no verifier, and the biconditional is what forbids half a pair.
    constraint ck_app_user_email_verifier_known
        check (email_verified_by in ('GOOGLE', 'KAKAO')),
    -- The SHAPE of the key, because a merge key is only as safe as the values
    -- the column can hold. '' is the case that matters: providers hand back ""
    -- for an absent optional field instead of omitting it, and an empty string
    -- is a perfectly legal varchar. Stored, it is a VERIFIED address, and every
    -- later empty-email login merges onto it — not a split but ONE app_user
    -- shared by strangers, each seeing the others' weddings, guests and
    -- contacts, with whoever registered first holding the row.
    --
    -- The whitespace half is the same argument one step out: to this schema
    -- ' kim@gmail.com' and 'kim@gmail.com' are two rows and two people.
    -- Normalising "" to NULL and trimming before write is #37's job; this is
    -- what makes forgetting it loud instead of silent. It deliberately does not
    -- validate an address — one @ with something on each side and no whitespace
    -- anywhere is everything a merge key needs, and a stricter pattern would
    -- start refusing real people at login.
    constraint ck_app_user_email_shape
        check (email is null or (email like '%_@_%' and email !~ '[[:space:]]'))
);

-- On lower(email COLLATE "C") — not on email, and not on a bare lower(email).
--
-- lower() first. Google returning `Kim@Gmail.com` and Kakao returning
-- `kim@gmail.com` is one person, and splitting them into two accounts looks to
-- the couple like the ledger vanished — the loudest possible failure for a merge
-- key. Lowercasing before write stays the application's job; this index is what
-- makes forgetting it a constraint violation instead of a duplicate person.
--
-- COLLATE "C" second, and TYPE IT: it changes what uniqueness MEANS, so an index
-- created without it is a valid index that refuses rows this one accepts. Under
-- this database's own ctype, lower() is not injective:
--     select lower('KİM@X.COM') = lower('KIM@X.COM');   -- t
--     select 'KİM@X.COM' = 'KIM@X.COM';                 -- f
-- Two different addresses, one merge key, and the second person seated on the
-- first one's account. "C" makes the fold ASCII-only, which is exactly the
-- case-folding a merge key needs and no more. It also pins the btree's own
-- comparison to byte order, which matters because an index over a collatable
-- expression can be silently invalidated by a glibc or ICU version change — and
-- an invalid unique index stops catching duplicates on the merge key. Nothing
-- pins this server's locale or locale provider (Testcontainers gives
-- en_US.utf8/libc; a managed Postgres 16 may be ICU). Same class as the header's
-- warning about `ddl-auto: validate`, and worse: validate misses a WIDTH,
-- collation changes an IDENTITY. Held by AppUserSchemaTest, which reads the
-- definition back rather than trusting the container it was given.
--
-- No live attack today — none of the three providers issues a verified non-ASCII
-- address — so what this defends against is the drift, in a file typed by hand.
--
-- The application side must use the SAME function, and it is not the obvious
-- one: Kotlin's String.lowercase() is full Unicode case mapping, so it is NOT
-- lower(... collate "C") — 'İ' comes back as two code points. #37 normalises
-- with an ASCII-only lowercase and looks the row up with this expression, or the
-- lookup misses the very row the index forbids it to duplicate (#82).
--
-- Still partial on `email is not null`, because most accounts will have no
-- email at all (Kakao/Naver optional consent) and NULLs must not collide.
-- No `deleted_at` half: app_user is not user-deletable and carries no such
-- column (notes/2026-08-10-decision-soft-delete.md).
create unique index ux_app_user_email
    on app_user (lower(email collate "C"))
    where email is not null;

create table oauth_identity (
    id               bigint generated by default as identity primary key,
    user_id          bigint      not null references app_user (id),
    -- GOOGLE / KAKAO / NAVER. varchar, not an enum: a fourth provider must be
    -- a deploy.
    provider         varchar(20) not null,
    -- The provider's own subject id. Length is the provider's to decide and
    -- none of the three document a bound, so this is generous on purpose.
    provider_user_id varchar(255) not null,
    created_at       timestamptz not null,
    constraint ux_oauth_identity_provider_subject unique (provider, provider_user_id)
);

-- Postgres does not index a foreign key for you, and login reads this by user.
create index ix_oauth_identity_user on oauth_identity (user_id);


-- ---------------------------------------------------------------------------
-- The wedding, and who may see it.
-- ---------------------------------------------------------------------------

create table wedding (
    id                    bigint generated by default as identity primary key,
    -- Onboarding asks for exactly this and the two names
    -- (notes/2026-08-07-design-screens-and-flow.md).
    wedding_date          date         not null,
    groom_name            varchar(100) not null,
    bride_name            varchar(100) not null,
    -- 보증인원 — the VENUE's number, never ours. Nullable because couples sign
    -- up before booking a venue; the ledger works fully without it and the
    -- comparison simply does not render until it is set.
    guaranteed_headcount  integer,
    created_by            bigint       not null references app_user (id),
    created_at            timestamptz  not null,
    updated_at            timestamptz  not null,
    deleted_at            timestamptz,
    -- An invariant, not policy: there is no reading of a contracted guarantee
    -- under which a negative is meaningful, and "not agreed yet" is already
    -- spelled NULL. Unlike the varchar value sets, a positivity rule will never
    -- need an ALTER, so it belongs in the schema rather than in a validator.
    constraint ck_wedding_guaranteed_headcount check (guaranteed_headcount > 0)
);

create table membership (
    id         bigint      generated by default as identity primary key,
    wedding_id bigint      not null references wedding (id),
    user_id    bigint      not null references app_user (id),
    created_at timestamptz not null,
    deleted_at timestamptz
);

-- PARTIAL, not a plain UNIQUE (wedding_id, user_id). A soft-deleted row keeps
-- occupying its unique slot, so removing a partner and re-inviting them would
-- be blocked by the dead membership
-- (notes/2026-08-10-decision-soft-delete.md).
create unique index ux_membership_wedding_user
    on membership (wedding_id, user_id)
    where deleted_at is null;

-- The hot path of the whole product: every request resolves
-- user -> membership -> wedding.
create index ix_membership_user
    on membership (user_id)
    where deleted_at is null;


-- ---------------------------------------------------------------------------
-- Meal types. Configured per wedding, because venues differ irreducibly.
-- Default is a single type, so the simple case configures nothing.
-- ---------------------------------------------------------------------------

create table meal_type (
    id         bigint      generated by default as identity primary key,
    wedding_id bigint      not null references wedding (id),
    -- 기본 / 유아식 / 글루텐프리 — the couple's own words, from their venue
    -- contract.
    name       varchar(50) not null,
    created_at timestamptz not null,
    -- A type already assigned to guests cannot be deleted at all (2026-08-06);
    -- this column is for the unused-type case.
    deleted_at timestamptz,
    -- Implied by the primary key and therefore useless as a constraint. It
    -- exists solely to be the TARGET of guest_meal_count's composite FK — see
    -- the block on that table. It cannot be partial on deleted_at: Postgres
    -- will only point a foreign key at a full unique constraint or index.
    constraint ux_meal_type_id_wedding unique (id, wedding_id)
);

create unique index ux_meal_type_wedding_name
    on meal_type (wedding_id, name)
    where deleted_at is null;


-- ---------------------------------------------------------------------------
-- Intake events. Neither carries deleted_at: they are records of things that
-- happened, and deleting one breaks hash idempotency.
-- ---------------------------------------------------------------------------

create table guest_import (
    id            bigint      generated by default as identity primary key,
    wedding_id    bigint      not null references wedding (id),
    -- SHA-256 of the uploaded file, hex. The row exists from the moment the
    -- file is received (notes/2026-08-10-decision-soft-delete.md) so that
    -- guest_change's FK to "the import that caused it" always has a target.
    file_hash     varchar(64) not null,
    -- RECEIVED / SUCCEEDED / FAILED. varchar, not an enum.
    status        varchar(20) not null,
    -- Set when a LATER import of the same file takes over as the authority for
    -- that hash — i.e. the couple deliberately re-ran a file we had already
    -- processed. NULL means this row is still the live one.
    --
    -- This is not a soft delete and not a revision of history. The original
    -- row's own fields are untouched; this appends a later fact ("this import
    -- is no longer the authority for this file"), which is exactly what an
    -- append-only event record is allowed to accrue. guest_import still has no
    -- deleted_at and still cannot be removed.
    superseded_at timestamptz,
    uploaded_by   bigint      not null references app_user (id),
    created_at    timestamptz not null
);

-- Scoped to the wedding, to SUCCEEDED, and to the LIVE row, and all three
-- halves are load-bearing.
-- Global would let another wedding's import block ours, and the refusal itself
-- would be an existence oracle. Unconditional would let an import that crashed
-- mid-parse lock that file forever. And without `superseded_at is null` there
-- could be at most one SUCCEEDED row per file EVER, so a deliberate re-run of
-- the same file could not be recorded at all — which collides with the
-- soft-delete decision (2026-08-10): "삭제된 하객이 파일에 있으면 되살릴지
-- 묻는다" can only fire on a file that actually gets processed, and by far the
-- commonest case is a parent re-sending the identical file.
--
-- A forced re-import is therefore two statements in ONE transaction: stamp
-- superseded_at on the row that is currently live, and make this run's own row
-- SUCCEEDED. Note that the second is an UPDATE, not an INSERT — the forced
-- run's row already exists as RECEIVED, per the writer shape documented below,
-- and this is the same tx as the guest writes. The invariant is unchanged in
-- strength: at most one LIVE SUCCEEDED row per (wedding, hash).
--
-- WHAT SERIALISES TWO CONCURRENT FORCES IS THE ORDERING, NOT THE INDEX, and an
-- earlier version of this comment got that wrong in a way worth spelling out,
-- because it is the version a reader reconstructs on their own.
--
-- What serialises is the row lock the supersede UPDATE takes on the live row,
-- and it covers the guest writes only if the supersede is the FIRST statement
-- of the processing transaction — see the writer contract below, which states
-- that ordering as a rule. Under it the loser blocks on the winner's
-- uncommitted UPDATE; when the winner commits, READ COMMITTED re-evaluates the
-- predicate against the updated row (EPQ), `superseded_at is null` is now
-- false, and the loser gets UPDATE 0 before it has loaded a single guest.
--
-- With the supersede anywhere later — next to the flip, the natural place to
-- put bookkeeping — nothing serialises at all. Reproduced on Postgres 16 with
-- two concurrent forces of one (wedding_id, file_hash), each shaped
-- `matcher load -> guest writes -> supersede -> flip`: BOTH COMMITTED. The
-- loser's supersede ran after the winner had committed, resolved the winner's
-- brand-new row as the live one, superseded that, and then found an empty slot
-- for its own flip. The index invariant held perfectly — exactly one live
-- SUCCEEDED row — and every guest in the file was written twice, from a matcher
-- snapshot taken before the winner's guests existed. That is verbatim the
-- double write the second alternative below is rejected for.
--
-- Two alternatives will be proposed again, so: a `forced boolean` in the key
-- allows exactly two rows and blocks the SECOND force; exempting forced rows
-- from the index entirely reopens the concurrent double-submit that writes 380
-- guests twice. Neither is a variant of this — both drop the invariant.
--
-- The force button and its UX are #20/#21. This is the column and the index.
--
-- WHAT THIS INDEX DOES NOT DO, and the contract #20 owes it. Two concurrent
-- uploads of the same file both insert a RECEIVED row without conflict — the
-- partial predicate does not match either of them. The violation fires only on
-- the UPDATE to SUCCEEDED, which is AFTER the second run has parsed the file
-- and written its guests. On its own the index therefore catches the
-- bookkeeping and misses the data.
--
-- It is only sufficient if the writer is shaped this way, and the ORDER is part
-- of the shape:
--   * the RECEIVED insert commits on its own, because guest_change's FK needs
--     that row to exist while the parse is still running;
--   * on a forced run, the supersede UPDATE is the FIRST statement of the
--     processing transaction — before the matcher loads the wedding's guests,
--     not merely before the flip. That is what puts the guest writes inside the
--     lock's reach; see above for what happens when it does not. An ordinary
--     run issues no supersede at all: a hash that is already live is refused
--     before any processing, which is the idempotency rule itself;
--   * `0 rows superseded` ABORTS the import. This half carries as much weight
--     as the ordering: a writer that reads UPDATE 0 as "nothing is live, so
--     re-resolve and supersede whatever is live now" walks straight back into
--     the same double write by a second route. Zero rows on a force means
--     another transaction took the slot while we waited, and the premise of the
--     force is gone;
--   * the guest writes and the flip to SUCCEEDED are ONE transaction, so the
--     unique violation rolls the guests back with the status. This is the
--     backstop, not the mechanism — it is what catches two concurrent
--     FIRST-TIME imports of one file, which have no live row to serialise on.
-- Written here rather than only in #20 because the index is what makes the
-- rule enforceable, and a future reader will find this comment before the
-- service.
create unique index ux_guest_import_wedding_file
    on guest_import (wedding_id, file_hash)
    where status = 'SUCCEEDED' and superseded_at is null;

create table email_ingest (
    id                  bigint      generated by default as identity primary key,
    wedding_id          bigint      not null references wedding (id),
    -- Nullable, and the null is the point: raw pasted text is kept only until
    -- the derived values are confirmed plus a bounded window, then deleted for
    -- personal-data minimisation (2026-07-30) — while the ROW survives,
    -- because the soft-delete record forbids deleting an ingest. Purging is
    -- therefore nulling this column, not removing the row.
    -- Rendered back to the couple as text, never as HTML.
    raw_text            text,
    -- When the purge above actually ran. `raw_text IS NULL` alone cannot tell
    -- "purged on schedule" from "never stored", so without this column nobody
    -- can audit whether the retention promise is being kept — and an unaudited
    -- retention promise is the kind of claim a privacy review asks for evidence
    -- of. NULL here means raw_text has never been purged.
    raw_text_purged_at  timestamptz,
    -- SHA-256 of the pasted body, hex. Unlike an import file this only warns —
    -- hence an ordinary index below, not a unique one.
    body_hash           varchar(64) not null,
    -- PARSED / UNSUPPORTED / ... — varchar, not an enum.
    status              varchar(20) not null,
    created_by          bigint      not null references app_user (id),
    created_at          timestamptz not null
);

create index ix_email_ingest_wedding_body_hash
    on email_ingest (wedding_id, body_hash);


-- ---------------------------------------------------------------------------
-- The ledger.
-- ---------------------------------------------------------------------------

create table guest (
    id                   bigint       generated by default as identity primary key,
    wedding_id           bigint       not null references wedding (id),
    -- 100 rather than 255: this holds a person's name, and the reason for the
    -- headroom is foreign names and 4-syllable Korean names, not a URL.
    -- It must never be tightened below what the entity mapping declares —
    -- validate will not tell you.
    name                 varchar(100) not null,
    side                 wedding_side not null,
    -- One of seven: FAMILY / RELATIVE / COUSIN / PARENTS_GUEST / FRIEND /
    -- COWORKER / OTHER. The list changed twice in one day; assume it changes
    -- again, which is why this is varchar and not an enum. Aggregation splits
    -- on this column only.
    group_category       varchar(30)  not null,
    -- The couple's free label ("대학교 동아리 친구들"), and where an unmapped
    -- 관계 from an import file is preserved verbatim. Never aggregated on:
    -- free labels fracture on typing variants.
    group_label          varchar(100),
    -- As entered. An import file usually carries the whole number; the vendor
    -- email carries only the last four digits. Normalising for matching is the
    -- matcher's job, in memory, not a stored derived column.
    contact              varchar(30),
    -- 배려사항 — free text, belongs to the person, carries forward to seating.
    accessibility_note   varchar(500),
    -- Expected is what the couple typed; confirmed is what was verified.
    -- Confirmed is nullable because blank is UNKNOWN, never zero — the
    -- aggregation falls back to expected and counts the guest as 확인 필요.
    expected_attending   boolean      not null,
    confirmed_attending  boolean,
    -- 참석 인원: the guest plus whoever they bring, not the companion count.
    -- The vendor channel's 추가 동행 인원 is converted on the way in.
    expected_party_size  integer      not null,
    confirmed_party_size integer,
    created_by           bigint       not null references app_user (id),
    created_at           timestamptz  not null,
    updated_by           bigint       not null references app_user (id),
    updated_at           timestamptz  not null,
    deleted_at           timestamptz,
    -- A party of zero people is not a party; 불참 is spelled
    -- confirmed_attending = false, not party size 0 — and with `lifecycle` gone
    -- (see the header) there is no second column that could also mean it.
    -- Strictly positive on both slots, and NULL passes a CHECK, so the confirmed
    -- slot keeps meaning "not verified yet".
    --
    -- What this does NOT pin down, since nothing else will say so: the schema
    -- still admits confirmed_attending = false alongside a non-null
    -- confirmed_party_size. Which one the aggregation reads first is #17's, and
    -- the answer has to be attendance — a party size on a 불참 guest is stale
    -- data, not a claim.
    constraint ck_guest_expected_party_size check (expected_party_size > 0),
    constraint ck_guest_confirmed_party_size check (confirmed_party_size > 0),
    -- Implied by the primary key; exists solely as the target of
    -- guest_meal_count's composite FK. Same non-partial reasoning as
    -- ux_meal_type_id_wedding.
    constraint ux_guest_id_wedding unique (id, wedding_id)
);

-- Every ledger read is "this wedding, not deleted". Partial so the index does
-- not carry rows no screen will ever show.
--
-- Note what that costs, because it is invisible otherwise: the import matcher
-- is the one query that must SEE deleted rows, so its predicate does not match
-- this index and it will sequential-scan the wedding's guests. That is
-- acceptable at v1 volumes (200–800 rows per wedding, loaded once per import
-- and matched in memory) and it is not covered by anything else — the matcher
-- has no index of its own. If it ever needs one, the shape is an unfiltered
-- index on wedding_id, not a change to this one.
create index ix_guest_wedding
    on guest (wedding_id)
    where deleted_at is null;

create table guest_meal_count (
    id              bigint  generated by default as identity primary key,
    -- WEDDING_ID HERE IS AN INTEGRITY DEVICE, NOT A ROOT MARKER. Read this
    -- before citing it as precedent.
    --
    -- The standing rule is unchanged: every wedding-scoped aggregate ROOT
    -- carries wedding_id, and anything reached only through its root does not.
    -- guest_meal_count is still not a root, and this column does not make it
    -- one. It is here for one reason: to make a MIXED-wedding row
    -- UNREPRESENTABLE — one whose guest and whose meal type belong to different
    -- weddings. Read that word narrowly; the paragraph on the FKs below says
    -- what it does not cover, and the gap is the interesting part.
    --
    -- SO IT IS AN FK COMPONENT AND NEVER A QUERY PREDICATE. Every read of this
    -- table joins `guest` and filters `guest.deleted_at is null`; nothing
    -- filters this table on its own wedding_id. The column is exactly what
    -- makes the wrong query writable, and the wrong query is the natural one:
    --     select sum(expected_count) from guest_meal_count where wedding_id = ?
    -- silently counts the meals of soft-deleted 하객, because @SQLRestriction
    -- does not reach a native query
    -- (notes/2026-08-10-decision-soft-delete.md, consequence 1). It does not
    -- throw, it over-counts, and over-counting 보증인원 is money. The correct
    -- shape joins:
    --     select sum(gmc.expected_count) from guest_meal_count gmc
    --       join guest g on g.id = gmc.guest_id
    --      where g.wedding_id = ? and g.deleted_at is null
    -- That soft-delete record predates this column, so its warning was written
    -- about tables that did not yet include the one place it bites hardest.
    -- GuestMealCountSchemaTest holds the regression.
    --
    -- No `references wedding (id)`, and that omission is deliberate rather than
    -- missed — it is the only wedding_id in this file without one. Both
    -- composite FKs below already point at a parent whose own wedding_id
    -- references wedding, so the value here cannot be a wedding that does not
    -- exist. A third constraint would enforce nothing and cost an index probe
    -- per write. Do not "fix" it while typing.
    --
    -- The hole it closes: meal_type_id arrives in the request body (#14), so it
    -- never passes through CurrentWedding resolution. With single-column FKs, a
    -- row joining wedding 1's guest to wedding 2's meal type inserts cleanly —
    -- and the API then answers differently for a nonexistent id (FK violation)
    -- than for another wedding's id (success), which is precisely the
    -- wedding-id oracle that
    -- notes/2026-08-10-decision-cross-tenant-status-code.md exists to deny.
    -- Service-layer validation would also close THAT, but only where someone
    -- remembers to write it; the composite FKs below close it for every writer
    -- that will ever exist.
    --
    -- #80 (the wedding_id allowlist meta-test) MUST carry this table as an
    -- explicit exception: it has the column and is not a root.
    --
    -- No deleted_at: it is not a row a user deletes, it is a count they set to
    -- zero.
    wedding_id      bigint  not null,
    guest_id        bigint  not null,
    meal_type_id    bigint  not null,
    expected_count  integer not null,
    confirmed_count integer,
    -- Composite, and that is the whole mechanism: both parents must agree with
    -- this row's wedding_id, so guest and meal type are forced into the same
    -- wedding by the database. They replace the single-column FKs rather than
    -- supplementing them — each subsumes the one it replaces.
    --
    -- WHAT THEY DO NOT CLOSE, because "unrepresentable" reads as more than it
    -- says. They force the row to be INTERNALLY consistent, not to be OWNED by
    -- the caller's wedding. A row wholly inside another wedding inserts cleanly:
    --     insert into guest_meal_count (wedding_id, guest_id, meal_type_id, expected_count)
    --     values (2, 200, 20, 2);   -- issued by a wedding-1 caller
    -- All three columns agree and the FKs have nothing to object to. The
    -- plausible #14 implementation — load the guest, take its wedding_id — writes
    -- exactly that row into a stranger's ledger. Worse, the outcomes then differ:
    -- a second identical attempt returns ux_guest_meal_count_guest_type where the
    -- first returned success, which is a cross-wedding EXISTENCE ORACLE on the
    -- victim's guests — the same thing
    -- notes/2026-08-10-decision-cross-tenant-status-code.md denies. Only the
    -- resolver closes it; that is #5/#14's and no constraint on this table will
    -- ever do it.
    --
    -- And they do not imply a LIVE parent. Both targets are non-partial unique
    -- constraints, necessarily — Postgres will not point an FK at a partial
    -- index — so a soft-deleted guest and a soft-deleted meal_type each still
    -- accept new rows here. Same wedding only, so it is not an isolation
    -- problem; but "a type in use cannot be deleted" (2026-08-06) and the
    -- soft-delete filter have no database backstop on this table, and
    -- @SQLRestriction does not reach it. #10/#14 own that test.
    constraint fk_guest_meal_count_guest
        foreign key (guest_id, wedding_id) references guest (id, wedding_id),
    constraint fk_guest_meal_count_meal_type
        foreign key (meal_type_id, wedding_id) references meal_type (id, wedding_id),
    constraint ux_guest_meal_count_guest_type unique (guest_id, meal_type_id),
    -- >= 0 here, unlike party size: zero is a meaningful count. "3명 중 2명만
    -- 식사" makes the other type's row a real, deliberate zero.
    constraint ck_guest_meal_count_expected check (expected_count >= 0),
    constraint ck_guest_meal_count_confirmed check (confirmed_count >= 0)
);

-- Supports the lookup behind "a type in use cannot be deleted" (2026-08-06).
-- UNDECIDED, and the index does not settle it: whether "in use" means a row
-- exists for this type, or a row with a non-zero count exists. Those differ for
-- a guest whose count was set to 0, and #10 owns the answer. If it turns out to
-- be the non-zero reading, this index still serves it — just less selectively.
create index ix_guest_meal_count_meal_type on guest_meal_count (meal_type_id);


-- ---------------------------------------------------------------------------
-- The audit log. Append-only: no deleted_at, because a deletable audit log is
-- not an audit log. This is what makes "이 숫자 누가 바꿨어?" answerable.
-- ---------------------------------------------------------------------------

create table guest_change (
    id              bigint      generated by default as identity primary key,
    -- Its own aggregate root, so it carries wedding_id: change rows are never
    -- loaded with a guest (thousands of them) and are queried independently.
    wedding_id      bigint      not null references wedding (id),
    guest_id        bigint      not null references guest (id),
    -- One row per changed FIELD, not per save.
    field_name      varchar(50) not null,
    -- text rather than a sized varchar: these hold the rendered old and new
    -- value of whatever field changed, so the widest column in `guest` is a
    -- floor that would have to be chased every time one grows. Null means the
    -- field was empty on that side, which for a nullable column is a real
    -- change worth recording.
    old_value       text,
    new_value       text,
    -- MANUAL / VENDOR_EMAIL / IMPORT. varchar, not an enum.
    source          varchar(20) not null,
    changed_by      bigint      not null references app_user (id),
    changed_at      timestamptz not null,
    -- Exactly one of these is set when source names a channel, and neither
    -- when it is MANUAL. Not expressed as a CHECK constraint: #25 owns the
    -- write path and has not been built, and a hand-applied constraint that
    -- turns out slightly wrong is more expensive to undo than to add.
    email_ingest_id bigint references email_ingest (id),
    guest_import_id bigint references guest_import (id)
);

-- "This wedding's history", newest first.
create index ix_guest_change_wedding_changed_at
    on guest_change (wedding_id, changed_at desc);

-- "Who changed this number", for one guest.
create index ix_guest_change_guest_changed_at
    on guest_change (guest_id, changed_at desc);
