-- The couple's session. Left out of V1 on purpose: its columns follow from a
-- mechanism that had not been designed yet (V1__baseline_schema.sql header,
-- notes/2026-08-12-decision-login-slice-by-provider.md), and #37 is where it was.
--
-- SAME RULES AS V1. Flyway applies this in the test suite and nowhere else; the
-- real database gets it typed by hand, wrapped in an explicit BEGIN; ... COMMIT;
-- (notes/2026-08-09-decision-schema-ownership.md). Column sizes are load-bearing
-- and `ddl-auto: validate` does not check them.
--
-- WHY TWO COLUMNS AND NOT ONE HASH, in short — the full argument, including the
-- version of it that was WRONG, is notes/2026-08-12-decision-session-token-shape.md.
--
-- The cookie carries `<selector>.<verifier>`. The row is found by `selector`, and
-- the `verifier` is then compared as a SHA-256 hash, in constant time, by the
-- application (notes/2026-07-30-decision-network-security.md, Tokens).
--
-- A single `sha256(token)` under a unique index would have been shorter and would
-- NOT have been insecure: what it compares is hash against hash, and a leaked hash
-- prefix is not a route to a 256-bit preimage. What it would not have been is
-- CHECKABLE — the only comparison in that design happens inside a btree, which
-- cannot be removed and therefore cannot be watched failing. Splitting the token
-- gives the comparison a place to live where deleting it turns a test red.
--
-- Neither half is stored in a form that can be replayed: `selector` is a public
-- lookup handle carrying no authority, and `verifier_hash` is a hash. A database
-- leak therefore hands over no working session — which is true of the shorter
-- design too, and is why it was never the unsafe option.
create table user_session (
    id            bigint      generated by default as identity primary key,
    -- 16 CSPRNG bytes, base64url without padding — exactly 22 characters today.
    -- Declared wider than that on purpose: this is a lookup handle, not a secret,
    -- and a length that is exact to the byte turns any future change to the
    -- encoding into a failed INSERT at login rather than a wider column.
    selector      varchar(32) not null,
    -- SHA-256 of the verifier, hex. The verifier itself is 32 CSPRNG bytes and is
    -- never stored, in any form, anywhere.
    verifier_hash varchar(64) not null,
    user_id       bigint      not null references app_user (id),
    -- The ABSOLUTE expiry anchor. `server.servlet.session.timeout` cannot express
    -- this — it only ever gives idle — so absolute expiry is enforced by the
    -- application against this column, and a configuration that looks complete is
    -- exactly how it gets forgotten (#5's handover comment).
    created_at    timestamptz not null,
    -- The IDLE expiry anchor, touched on every resolved request.
    last_seen_at  timestamptz not null,
    -- Set when a session stops being usable while its row stays readable. Today
    -- the only writer is the re-issue on login (session fixation): the session the
    -- browser presented is revoked in the same transaction that mints its
    -- replacement. Logout, when it lands, writes the same column.
    --
    -- Not `deleted_at`: nothing here is a user-deletable row, so this is not the
    -- soft delete of notes/2026-08-10-decision-soft-delete.md and it carries none
    -- of that record's consequences (no partial unique index is needed below —
    -- see the index comment).
    revoked_at    timestamptz
);

-- UNIQUE and NOT partial, unlike every unique index in V1.
--
-- The partial-index rule exists because a soft-deleted row must not keep
-- occupying a slot a live row needs (2026-08-10, consequence 3). There is no such
-- slot here: `selector` is 128 bits of CSPRNG, so a revoked row can only block a
-- new one by colliding, and a collision is the event this index exists to refuse.
-- Unconditional uniqueness is what makes "one selector resolves to at most one
-- session" true of the whole table rather than of its live part.
create unique index ux_user_session_selector on user_session (selector);

-- Postgres does not index a foreign key for you, and revoking a user's sessions
-- reads this by user.
create index ix_user_session_user on user_session (user_id);
