-- The couple's two seats, and the wedding's entitlement.
--
-- SAME RULES AS V1. Flyway applies this in the test suite and nowhere else; the
-- real database gets it typed by hand, wrapped in an explicit BEGIN; ... COMMIT;
-- (notes/2026-08-09-decision-schema-ownership.md). Column sizes are load-bearing
-- and `ddl-auto: validate` does not check them — nor does it check any index or
-- constraint below.
--
-- WHY THIS EXISTS, in short — the full argument is
-- notes/2026-08-22-decision-the-couples-two-seats.md and
-- notes/2026-08-22-decision-entitlement-belongs-to-the-wedding.md.
--
-- A wedding has exactly two seats, 신랑 and 신부, and a seat carries a person's
-- NAME and — once they arrive — their ACCOUNT. V1 held those in two places:
-- `wedding.groom_name`/`bride_name` for the names, a `membership` row for the
-- account, and NOTHING joining them. Two consequences, and they are the reason
-- this file is not a rename: "this account is the 신부" was not expressible even
-- with both accounts present, and onboarding asked one partner to type the
-- other's name. A seat is the concept both halves were fragments of.


-- ---------------------------------------------------------------------------
-- The seats. Replaces `membership`, which is dropped at the bottom of this file.
-- ---------------------------------------------------------------------------
create table wedding_party (
    id         bigint       generated by default as identity primary key,
    wedding_id bigint       not null references wedding (id),
    side       wedding_side not null,
    -- NULL until that person says who they are, which is the point: the seat can
    -- exist before its occupant does, so nobody types anybody else's name.
    -- 100 matches guest.name for the same reason — foreign names and 4-syllable
    -- Korean names, not a URL.
    name       varchar(100),
    -- NULL means the seat is still waiting. THIS COLUMN IS THE MEMBERSHIP: a
    -- person is a member of a wedding exactly when they hold one of its two
    -- seats, so `user -> seat -> wedding` replaces `user -> membership -> wedding`
    -- as the resolution every scoped request runs.
    user_id    bigint       references app_user (id),
    -- When the seat was claimed, which is not created_at: the partner's seat is
    -- created with the wedding and claimed whenever they accept (#9).
    joined_at  timestamptz,
    created_at timestamptz  not null,
    updated_at timestamptz  not null,
    -- Kept — unlike wedding_subscription below, where a term ends rather than
    -- being removed — because a seat has to be RELEASABLE. `wedding` is soft
    -- deleted rather than removed, and without this its seats would go on
    -- occupying ux_party_user and bar both people from ever joining another
    -- wedding. Clearing user_id instead would release them and lose who held it.
    deleted_at timestamptz
);

-- One 신랑 seat and one 신부 seat per wedding. PARTIAL for the reason
-- ux_membership_wedding_user was: a soft-deleted row keeps occupying a plain
-- unique slot, and re-creating what was removed would then be refused
-- (notes/2026-08-10-decision-soft-delete.md).
create unique index ux_party_wedding_side
    on wedding_party (wedding_id, side)
    where deleted_at is null;

-- "한 사람은 웨딩 하나" (2026-08-21), moved here from ux_membership_user with the
-- rule intact and only its column changed. It is also the hot path of the whole
-- product. `user_id is not null` is the half that is new: an UNCLAIMED seat has
-- to be legal, and multiple NULLs do not collide in a partial index anyway —
-- spelling it out keeps the intent readable next to the rule it carries.
create unique index ux_party_user
    on wedding_party (user_id)
    where deleted_at is null and user_id is not null;


-- ---------------------------------------------------------------------------
-- The entitlement, as a TIMELINE OF TERMS rather than one mutable row.
--
-- 권리는 웨딩에 붙고 결제 주체만 사람이다. The Wedding is the top-level unit, so
-- hanging the entitlement on a person would make "one seat can use this ledger
-- and the other cannot" representable — and that state must not be. It is also
-- why this is not a column on wedding_party: that table is keyed by seat, so
-- anything attached to it is per-person by construction.
--
-- A row is a TERM, not a status. When the payer changes — 신랑 stops, 신부 starts
-- — the live term takes an ended_at and a new one begins, so "who paid for July"
-- is still answerable afterwards. A single mutable payer column would answer it
-- until the day it mattered, and this is money.
-- ---------------------------------------------------------------------------
create table wedding_subscription (
    id                 bigint      generated by default as identity primary key,
    wedding_id         bigint      not null references wedding (id),
    -- Only 'FREE' is written today. varchar and not an enum for the reason
    -- group_category and status are: the value set is not decided and a new value
    -- is just a new word. WHAT free grants is an open question, deliberately —
    -- deciding a boundary before anyone has filled a ledger would be a guess.
    plan               varchar(30) not null,
    -- ACTIVE / PAST_DUE / CANCELED. Only ACTIVE is written until payment exists.
    status             varchar(20) not null,
    -- Who paid for THIS term. NULL = nobody did, which is exactly what a free
    -- term is. It references app_user and NOT wedding_party on purpose: the payer
    -- may later leave the wedding, and "they paid for that stretch" has to
    -- survive their seat being released.
    payer_id           bigint      references app_user (id),
    started_at         timestamptz not null,
    -- NULL = this is the live term. A value means it handed over to the next one.
    -- NOT a deletion, and not a revision: it appends a later fact, the same kind
    -- guest_import.superseded_at carries. There is deliberately no deleted_at on
    -- this table — a term is never removed, it ends.
    ended_at           timestamptz,
    -- What money already paid covers, which is NOT ended_at: paid through 8/31 and
    -- cancelled on 8/15 leaves the wedding entitled until 8/31. Exactly how a gap
    -- or an overlap between terms resolves needs the real cancellation and
    -- proration rules, and is open until payment is built.
    current_period_end timestamptz,
    created_at         timestamptz not null,
    updated_at         timestamptz not null,
    -- An invariant, not policy: a term ending before it starts is meaningless
    -- under every reading, and unlike the varchar value sets above this rule will
    -- never need an ALTER — so it belongs in the schema and not in a validator.
    constraint ck_subscription_term_order
        check (ended_at is null or ended_at >= started_at)
);

-- 웨딩당 활성 구독 1건. The restriction lives HERE and not in a service check, for
-- the reason ux_party_user does: a second live term is not representable, so two
-- tabs, a double-tapped button and two racing renewals all end in one term and one
-- refusal, however the requests interleave. Ended terms remain and do not occupy
-- the slot.
--
-- Note what this makes true of the FIRST payment. A wedding is created with a live
-- FREE term, so paying is a HANDOVER and never an insert on its own: end the free
-- term and start the paid one in one transaction. Skip that and the very first
-- payment violates this index — which is the failure to write a test for.
create unique index ux_subscription_live
    on wedding_subscription (wedding_id)
    where ended_at is null;


-- ---------------------------------------------------------------------------
-- The two fragments the seat replaces.
--
-- Dropped rather than left in place: a name column nothing reads is a name column
-- someone writes to, and two sources for one person's name is the bug this file
-- exists to remove.
-- ---------------------------------------------------------------------------
alter table wedding
    drop column groom_name,
    drop column bride_name;

drop table membership;
