-- The partner's invite: the one credential that seats a second person.
--
-- SAME RULES AS V1. Flyway applies this in the test suite and nowhere else; the
-- real database gets it typed by hand, wrapped in an explicit BEGIN; ... COMMIT;
-- (notes/2026-08-09-decision-schema-ownership.md). Column sizes are load-bearing
-- and `ddl-auto: validate` does not check them — nor does it check any index,
-- constraint or predicate below.
--
-- WHY THIS EXISTS, in short — the full argument is
-- notes/2026-08-22-decision-the-invite-link.md and
-- notes/2026-08-22-decision-the-partner-invite.md.
--
-- V1's header left this table out in as many words: "session, wedding invite,
-- vendor template — their columns follow from mechanisms that are not designed
-- yet". The mechanism is designed now. A couple's second seat is created empty by
-- `POST /weddings` (V3), and this table holds the ONE thing that can fill it: a
-- bearer token, minted by whoever already sits in the wedding, good for one day
-- and for one acceptance.
--
-- READ THIS BEFORE CHANGING ANY COLUMN: whoever holds a live token enters the
-- ledger and reads every 하객's contact. That is the premise every choice below
-- was made under.


-- ---------------------------------------------------------------------------
-- The invite.
--
-- SEAT_ID AND NO wedding_id, which is a deliberate answer to the standing rule
-- rather than an omission. The distinction that rule makes is checkable: an
-- integrity `wedding_id` appears in a composite FK to a parent's (id, wedding_id),
-- a root's does not (notes/2026-08-11-decision-baseline-schema-calls.md). What
-- earned `guest_meal_count` its copy was a `meal_type_id` arriving in a REQUEST
-- BODY, which bypasses CurrentWedding and made one wedding's guest joinable to
-- another's meal type. No id here ever arrives from a request: the issuing
-- endpoint is wedding-scoped and the server picks the seat off the RESOLVED
-- wedding, and acceptance addresses the row by token. So a `wedding_id` column
-- would be a second statement of what `wedding_party.wedding_id` already says,
-- needing a composite FK to keep the two honest — and the query that would have
-- justified it does not exist: this table is only ever read by `selector` or by
-- `seat_id`.
-- ---------------------------------------------------------------------------
create table wedding_invite (
    id            bigint      generated by default as identity primary key,
    -- WHICH SEAT, not which wedding. The row already exists (V3), so acceptance is
    -- an UPDATE of one identified seat rather than an insert — which is what makes
    -- "two people opened the same link" a lost update this schema and one row lock
    -- can answer, instead of a duplicate membership nothing would have caught.
    seat_id       bigint      not null references wedding_party (id),
    -- `<selector>.<verifier>`, exactly as `user_session` splits a session token
    -- and for the reason V2's header gives: the row is found by `selector` and the
    -- `verifier` is then compared as a SHA-256 hash, in constant time, by the
    -- application — so the comparison lives somewhere it can be watched failing.
    -- 16 CSPRNG bytes, base64url unpadded: 22 characters today, declared wider on
    -- purpose. A length exact to the byte turns a change of encoding into a failed
    -- INSERT rather than a wider column.
    selector      varchar(32) not null,
    -- SHA-256 of the verifier, hex. The verifier is 32 CSPRNG bytes and is never
    -- stored, in any form, anywhere — so a database dump hands over no working
    -- invite link, which is the property this table needs most.
    verifier_hash varchar(64) not null,
    -- Who minted it. An audit column, and the reason it is not `created_by` is
    -- that the pair below reads as one sentence with `issued_at`.
    issued_by     bigint      not null references app_user (id),
    issued_at     timestamptz not null,
    -- WHEN IT GOES STALE, stored rather than derived. 최대 1일 is the founder's
    -- call (notes/2026-08-22-decision-the-invite-link.md §1) and the application
    -- writes now + 1 day here; keeping the value on the row means a later change
    -- to that number leaves already-issued links keeping the promise they were
    -- made under. There is deliberately NO `check (expires_at <= issued_at + interval '1 day')`:
    -- the cap is product policy and would need an ALTER the day it moved, unlike
    -- the ordering below, which is meaningless under every reading.
    expires_at    timestamptz not null,
    -- SINGLE USE. Accepting consumes the token, and expiry and single use answer
    -- DIFFERENT failures — an unopened link going stale, and an opened link being
    -- replayed. A row with this set is spent forever; nothing clears it.
    accepted_at   timestamptz,
    -- Who spent it. Not redundant with `wedding_party.user_id`: a seat can be
    -- released and filled again, and "which account consumed this credential, and
    -- when" is the question an incident asks.
    accepted_by   bigint      references app_user (id),
    -- REISSUE KILLS THE PREVIOUS TOKEN (2026-08-22 §1): at most one live invite per
    -- seat, or a couple who taps 재발급 three times holds three live credentials in
    -- three places and the one-day life is undone by holding several at once.
    -- Every reissue writes this on the outgoing row in the same transaction that
    -- mints its replacement.
    --
    -- NOT `deleted_at`, and this table carries none: nothing here is a row a user
    -- deletes, so the soft-delete rule and its consequences do not apply
    -- (notes/2026-08-10-decision-soft-delete.md). This is `user_session.revoked_at`
    -- — a token that stops being usable while its row stays readable.
    revoked_at    timestamptz,
    -- An invariant and not policy, so it belongs here: a link that expires before
    -- it is issued is meaningless under every reading of these two columns.
    constraint ck_invite_expiry_after_issue
        check (expires_at > issued_at),
    -- The two halves of one fact. `accepted_at` without `accepted_by` is a spent
    -- token nobody can be shown to have spent; `accepted_by` without `accepted_at`
    -- is an acceptance that never happened.
    constraint ck_invite_accepted_together
        check ((accepted_at is null) = (accepted_by is null))
);

-- One selector resolves to at most one invite. UNIQUE and NOT partial, exactly as
-- ux_user_session_selector is and for the same reason: `selector` is 128 bits of
-- CSPRNG, so a spent or revoked row can only block a new one by colliding, and a
-- collision is the event this index exists to refuse. It is also the lookup the
-- accept path runs on every attempt, including every guess.
create unique index ux_wedding_invite_selector on wedding_invite (selector);

-- AT MOST ONE LIVE INVITE PER SEAT — the rule 재발급 turns on, held where it cannot
-- be forgotten. The application revokes the outgoing row inside the transaction
-- that inserts the replacement AND takes the seat's row lock first, so this index
-- is the backstop rather than the plan (the same division `ux_party_user` has with
-- WeddingService.claimSoleSeat): the lock decides what the API answers, the index
-- decides what may exist, including against psql.
--
-- PARTIAL on the two columns that end an invite's life rather than on `deleted_at`,
-- which this table does not have. An EXPIRED row still occupies the slot, and that
-- is correct: reissue revokes whatever it finds, so the slot is freed by the same
-- statement that needs it, and nothing else may quietly mint a second one.
create unique index ux_wedding_invite_live
    on wedding_invite (seat_id)
    where accepted_at is null and revoked_at is null;

-- And a PLAIN one over the same column, which is not a duplicate of it. The index
-- above is partial on the live rows, so it serves "is there a live invite for this
-- seat" and nothing else: every read of a seat's HISTORY — the retention sweep this
-- table will need for the same reason `user_session` did (#91), a "누가 언제
-- 발급했나" question, and Postgres's own check when a `wedding_party` row is hard
-- deleted — sees no index at all and scans. The cost of carrying it is one write per
-- issue on a table that gets a handful of rows per wedding.
create index ix_wedding_invite_seat on wedding_invite (seat_id);
