package com.donghaeng

import com.fasterxml.jackson.databind.ObjectMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.DynamicPropertyRegistry
import org.springframework.test.context.DynamicPropertySource
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.get
import java.nio.file.Files
import java.nio.file.Path

/**
 * **The seam's artifact.** `web/` generates its TypeScript types from
 * `api/build/openapi.json`, so this test both writes that file and is the only
 * thing that ever looks at what is in it
 * (`notes/2026-08-08-decision-build-workflow.md`, `#39`).
 *
 * Generated by asking the application, not by a Gradle plugin. The plugin runs
 * `bootRun`, which would need a datasource strategy for a database this repo
 * deliberately never migrates unattended; a boot test already has one
 * ([SharedPostgres]). The artifact is therefore a *test* artifact — which is why
 * `./gradlew build` writes it as a side effect, and why the `openapi` task in
 * `build.gradle.kts` exists to declare it as an output so a deleted file is
 * regenerated rather than reported UP-TO-DATE.
 *
 * `springdoc.api-docs.enabled=true` is set HERE and nowhere that ships. The
 * endpoint is a machine-readable map of every endpoint and DTO, and the deployed
 * image must keep answering 404 to it (`api/AGENTS.md`, Security posture;
 * asserted on the shipped image by CI's `docker` job).
 *
 * A `MOCK` web environment rather than a real port, and that is not only about
 * speed: springdoc writes the request's own base URL into `servers`, so a random
 * port would make the committed contract's bytes differ on every run.
 */
@SpringBootTest(
    properties = [
        "donghaeng.profile=test",
        "springdoc.api-docs.enabled=true",
    ],
)
@AutoConfigureMockMvc
class OpenApiDocumentTest {
    @Autowired
    private lateinit var mockMvc: MockMvc

    @Autowired
    private lateinit var objectMapper: ObjectMapper

    @Test
    fun `the document is written where web reads it`() {
        val document = generate()

        assertThat(Files.readString(DOCUMENT))
            .describedAs("%s is the file web/ runs openapi-typescript over", DOCUMENT.toAbsolutePath())
            .isEqualTo(document)
        assertThat(objectMapper.readTree(document)["openapi"].asText()).startsWith("3.")
    }

    @Test
    fun `the document declares exactly the endpoints the API has`() {
        // An exact set, not a `doesNotContain("/test-errors/domain")`. Two failures
        // are worth catching and only this shape catches both.
        //
        // A path that should not be there: the component scan is rooted at
        // `com.donghaeng` and the test classes are on that classpath, so a
        // `@RestController` declared in test source maps into EVERY `@SpringBootTest`
        // context — including this one, which then publishes it to `web/` as part of
        // the API (`#118`). `@TestComponent` is what keeps a test fixture inside its
        // own test, and this assertion is what notices when one forgets.
        //
        // A path that should be there and is not: `@Hidden`, a slipped `consumes`, a
        // controller that never got scanned. The frontend does not get a type for
        // it, and finds out by writing the call.
        //
        // So a new endpoint edits this list — in the same change as
        // `docs/api-spec.md`, which is where its MEANING goes.
        assertThat(pathsIn(generate()))
            .containsExactlyInAnyOrder(
                "/weddings",
                "/weddings/join",
                "/weddings/join/preview",
                "/weddings/{weddingId}",
                "/weddings/{weddingId}/seats/me",
                "/weddings/{weddingId}/invite",
                "/weddings/{weddingId}/guests",
                "/weddings/{weddingId}/headcount",
                "/auth/me",
                "/auth/logout",
            )
    }

    @Test
    fun `the seat name's length bound is published, on every request that carries one`() {
        // **`seam` cannot hold this and never will.** `openapi-typescript` drops
        // `maxLength`, so `web/src/lib/api-types.gen.ts` is byte-identical whether the
        // bound is in the document or not — verified by deleting it and regenerating.
        // The path-set assertion above does not reach schema members either. So the one
        // thing standing between `@SeatName`'s `@Size` and a published contract that
        // silently loses its length bound is this assertion.
        //
        // It matters because `#187` deleted three hand-written `@Schema(maxLength = 100)`
        // — correctly, since nothing kept them in step with the constant — on the
        // strength of springdoc walking the composed `@Size`. That is a mechanism, and a
        // mechanism nothing tests is a mechanism that leaves quietly.
        val schemas = objectMapper.readTree(generate())["components"]["schemas"]

        listOf("CreateWeddingRequest", "JoinWeddingRequest", "UpdateSeatNameRequest").forEach { schema ->
            assertThat(schemas[schema]["properties"]["name"]["maxLength"].asInt())
                .describedAs("%s.name must publish the varchar(100) bound `@SeatName` composes", schema)
                .isEqualTo(100)
        }
    }

    /** Writes the document as a side effect: this test is what produces the artifact. */
    private fun generate(): String {
        val document =
            mockMvc
                .get("/v3/api-docs")
                .andReturn()
                .response
                .also { assertThat(it.status).isEqualTo(200) }
                .contentAsString

        // Pretty-printed because a person reads this file when the frontend and the
        // backend disagree; `openapi-typescript` does not care either way.
        val pretty = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(objectMapper.readTree(document))
        Files.createDirectories(DOCUMENT.parent)
        Files.writeString(DOCUMENT, pretty)
        return pretty
    }

    private fun pathsIn(document: String): List<String> =
        objectMapper
            .readTree(document)["paths"]
            .fieldNames()
            .asSequence()
            .toList()

    companion object {
        /**
         * Relative to the project directory, which is what Gradle sets a `Test`
         * task's working directory to — `api/build/openapi.json`.
         */
        private val DOCUMENT: Path = Path.of("build", "openapi.json")

        @JvmStatic
        @DynamicPropertySource
        fun database(registry: DynamicPropertyRegistry) = SharedPostgres.publish(registry)
    }
}
